// <auto-generated />
using System;
using CGA.MetrologySystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CGA.MetrologySystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521214145_AddChecklistItemEvidenceImages")]
    partial class AddChecklistItemEvidenceImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.AlertaEnviada", b =>
                {
                    b.Property<int>("AlertaEnviadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlertaEnviadaId"));

                    b.Property<string>("Destinatarios")
                        .HasColumnType("text");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaReferencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FueExitosa")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("AlertaEnviadaId");

                    b.HasIndex("EquipoId");

                    b.ToTable("AlertasEnviadas");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.AuditoriaMetrologica", b =>
                {
                    b.Property<int>("AuditoriaMetrologicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditoriaMetrologicaId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CodigoEquipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsCritico")
                        .HasColumnType("boolean");

                    b.Property<int?>("EventoMetrologicoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("RolUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("UsuarioCorreo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("AuditoriaMetrologicaId");

                    b.ToTable("AuditoriasMetrologicas");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.AuditoriaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdministradorCorreo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdministradorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsuarioAfectadoCorreo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioAfectadoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditoriasUsuario");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.CaracteristicaMetrologicaEquipo", b =>
                {
                    b.Property<int>("CaracteristicaMetrologicaEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CaracteristicaMetrologicaEquipoId"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad")
                        .HasColumnType("text");

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("CaracteristicaMetrologicaEquipoId");

                    b.HasIndex("EquipoId");

                    b.ToTable("CaracteristicasMetrologicasEquipo");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.ConfiguracionControlEquipo", b =>
                {
                    b.Property<int>("ConfiguracionControlEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfiguracionControlEquipoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<string>("PeriodicidadUnidad")
                        .HasColumnType("text");

                    b.Property<int?>("PeriodicidadValor")
                        .HasColumnType("integer");

                    b.Property<bool>("PermitePorIngreso")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereControl")
                        .HasColumnType("boolean");

                    b.Property<int>("TipoEventoMetrologicoId")
                        .HasColumnType("integer");

                    b.HasKey("ConfiguracionControlEquipoId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("TipoEventoMetrologicoId");

                    b.ToTable("ConfiguracionesControlEquipo");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EquipoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CatalogoManejoOperacion")
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CondicionesOperacion")
                        .HasColumnType("text");

                    b.Property<string>("FabricanteLugarOrigen")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAdquisicion")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaPuestaFuncionamiento")
                        .HasColumnType("date");

                    b.Property<string>("FotoGoogleDriveFileId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FotoNombreArchivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FotoRutaArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GoogleDriveFolderId")
                        .HasColumnType("text");

                    b.Property<string>("Identificacion")
                        .HasColumnType("text");

                    b.Property<string>("MantenimientoFabricante")
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<int>("ResponsableInternoId")
                        .HasColumnType("integer");

                    b.Property<string>("Serie")
                        .HasColumnType("text");

                    b.Property<int>("TipoEquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("integer");

                    b.HasKey("EquipoId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("ResponsableInternoId");

                    b.HasIndex("TipoEquipoId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoCalibracionDato", b =>
                {
                    b.Property<int>("EventoCalibracionDatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventoCalibracionDatoId"));

                    b.Property<int>("EventoMetrologicoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCalibracion")
                        .HasColumnType("date");

                    b.Property<string>("GoogleDriveFileId")
                        .HasColumnType("text");

                    b.Property<int?>("LaboratorioId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreArchivoCertificado")
                        .HasColumnType("text");

                    b.Property<string>("NumeroCertificado")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("RutaCertificado")
                        .HasColumnType("text");

                    b.HasKey("EventoCalibracionDatoId");

                    b.HasIndex("EventoMetrologicoId")
                        .IsUnique();

                    b.HasIndex("LaboratorioId");

                    b.ToTable("EventosCalibracionDato");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoMantenimientoActividad", b =>
                {
                    b.Property<int>("EventoMantenimientoActividadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventoMantenimientoActividadId"));

                    b.Property<string>("DescripcionActividad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenciaContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EvidenciaGoogleDriveFileId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EvidenciaNombreArchivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EvidenciaRutaArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EventoMetrologicoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("EventoMantenimientoActividadId");

                    b.HasIndex("EventoMetrologicoId");

                    b.ToTable("EventosMantenimientoActividad");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoMantenimientoDato", b =>
                {
                    b.Property<int>("EventoMantenimientoDatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventoMantenimientoDatoId"));

                    b.Property<int>("EventoMetrologicoId")
                        .HasColumnType("integer");

                    b.Property<string>("GoogleDriveFileId")
                        .HasColumnType("text");

                    b.Property<string>("NombreArchivoPdf")
                        .HasColumnType("text");

                    b.Property<string>("RutaPdf")
                        .HasColumnType("text");

                    b.Property<int>("TipoMantenimientoId")
                        .HasColumnType("integer");

                    b.HasKey("EventoMantenimientoDatoId");

                    b.HasIndex("EventoMetrologicoId")
                        .IsUnique();

                    b.HasIndex("TipoMantenimientoId");

                    b.ToTable("EventosMantenimientoDato");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", b =>
                {
                    b.Property<int>("EventoMetrologicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventoMetrologicoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("Anulado")
                        .HasColumnType("boolean");

                    b.Property<string>("ComentariosAdicionales")
                        .HasColumnType("text");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsExtraordinario")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsHistorico")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoEquipoResultado")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaProxima")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JustificacionExtraordinario")
                        .HasColumnType("text");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ObservacionCargaHistorica")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ResponsableInternoId")
                        .HasColumnType("integer");

                    b.Property<int>("SubtipoEventoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEventoMetrologicoId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioAnulacionId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("UsuarioAnulacionNombre")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("EventoMetrologicoId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("ResponsableInternoId");

                    b.HasIndex("SubtipoEventoId");

                    b.HasIndex("TipoEventoMetrologicoId");

                    b.ToTable("EventosMetrologicos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoVerificacionDato", b =>
                {
                    b.Property<int>("EventoVerificacionDatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventoVerificacionDatoId"));

                    b.Property<int>("EventoMetrologicoId")
                        .HasColumnType("integer");

                    b.Property<string>("GoogleDriveFileId")
                        .HasColumnType("text");

                    b.Property<string>("NombreArchivoPdf")
                        .HasColumnType("text");

                    b.Property<string>("RutaPdf")
                        .HasColumnType("text");

                    b.HasKey("EventoVerificacionDatoId");

                    b.HasIndex("EventoMetrologicoId")
                        .IsUnique();

                    b.ToTable("EventosVerificacionDato");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoVerificacionResultado", b =>
                {
                    b.Property<int>("EventoVerificacionResultadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventoVerificacionResultadoId"));

                    b.Property<bool>("Cumple")
                        .HasColumnType("boolean");

                    b.Property<string>("DescripcionItem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenciaContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EvidenciaGoogleDriveFileId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EvidenciaNombreArchivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EvidenciaRutaArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EventoMetrologicoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("EventoVerificacionResultadoId");

                    b.HasIndex("EventoMetrologicoId");

                    b.ToTable("EventosVerificacionResultado");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EvidenciaEventoMetrologico", b =>
                {
                    b.Property<int>("EvidenciaEventoMetrologicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EvidenciaEventoMetrologicoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EventoMetrologicoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleDriveFileId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TipoEvidencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EvidenciaEventoMetrologicoId");

                    b.HasIndex("EventoMetrologicoId");

                    b.ToTable("EvidenciasEventoMetrologico");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.FichaTecnicaEquipo", b =>
                {
                    b.Property<int>("FichaTecnicaEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FichaTecnicaEquipoId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("CantidadEventosIncluidos")
                        .HasColumnType("integer");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaUltimaGeneracion")
                        .HasColumnType("date");

                    b.Property<string>("GoogleDriveFileId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NombreArchivoPdf")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RutaPdf")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("FichaTecnicaEquipoId");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.ToTable("FichasTecnicasEquipo");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.GoogleDriveCredential", b =>
                {
                    b.Property<int>("GoogleDriveCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GoogleDriveCredentialId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GoogleDriveCredentialId");

                    b.ToTable("GoogleDriveCredentials");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.HojaVidaEquipo", b =>
                {
                    b.Property<int>("HojaVidaEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HojaVidaEquipoId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("CantidadEventosIncluidos")
                        .HasColumnType("integer");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaUltimaGeneracion")
                        .HasColumnType("date");

                    b.Property<string>("GoogleDriveFileId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NombreArchivoPdf")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RutaPdf")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("HojaVidaEquipoId");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.ToTable("HojasVidaEquipo");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Laboratorio", b =>
                {
                    b.Property<int>("LaboratorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LaboratorioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Alcance")
                        .HasColumnType("text");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormaAcreditacion")
                        .HasColumnType("text");

                    b.Property<string>("NumeroAcreditacion")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .HasColumnType("text");

                    b.Property<string>("SitioWeb")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("LaboratorioId");

                    b.ToTable("Laboratorios");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.NotificacionEnviada", b =>
                {
                    b.Property<int>("NotificacionEnviadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificacionEnviadaId"));

                    b.Property<string>("Destinatarios")
                        .HasColumnType("text");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("EventoMetrologicoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaReferencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FueExitosa")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoNotificacion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("NotificacionEnviadaId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("EventoMetrologicoId");

                    b.ToTable("NotificacionesEnviadas");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.PlantillaEvento", b =>
                {
                    b.Property<int>("PlantillaEventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlantillaEventoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoEquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEventoMetrologicoId")
                        .HasColumnType("integer");

                    b.HasKey("PlantillaEventoId");

                    b.HasIndex("TipoEquipoId");

                    b.HasIndex("TipoEventoMetrologicoId");

                    b.ToTable("PlantillasEvento");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.PlantillaEventoItem", b =>
                {
                    b.Property<int>("PlantillaEventoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlantillaEventoItemId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("PlantillaEventoId")
                        .HasColumnType("integer");

                    b.HasKey("PlantillaEventoItemId");

                    b.HasIndex("PlantillaEventoId");

                    b.ToTable("PlantillasEventoItem");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProveedorId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("ProveedorId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.ResponsableInterno", b =>
                {
                    b.Property<int>("ResponsableInternoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResponsableInternoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cargo")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("ResponsableInternoId");

                    b.ToTable("ResponsablesInternos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.SubtipoEvento", b =>
                {
                    b.Property<int>("SubtipoEventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubtipoEventoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SubtipoEventoId");

                    b.ToTable("SubtiposEvento");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("TipoDocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoDocumentoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoDocumentoId");

                    b.ToTable("TiposDocumento");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.TipoEquipo", b =>
                {
                    b.Property<int>("TipoEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoEquipoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoEquipoId");

                    b.ToTable("TiposEquipo");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.TipoEventoMetrologico", b =>
                {
                    b.Property<int>("TipoEventoMetrologicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoEventoMetrologicoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoEventoMetrologicoId");

                    b.ToTable("TiposEventoMetrologico");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.TipoMantenimiento", b =>
                {
                    b.Property<int>("TipoMantenimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoMantenimientoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoMantenimientoId");

                    b.ToTable("TiposMantenimiento");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Ubicacion", b =>
                {
                    b.Property<int>("UbicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UbicacionId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UbicacionId");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Infrastructure.Identity.UsuarioSistema", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.AlertaEnviada", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.CaracteristicaMetrologicaEquipo", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Equipo", "Equipo")
                        .WithMany("CaracteristicasMetrologicas")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.ConfiguracionControlEquipo", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Equipo", "Equipo")
                        .WithMany("ConfiguracionesControl")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.TipoEventoMetrologico", "TipoEventoMetrologico")
                        .WithMany("ConfiguracionesControl")
                        .HasForeignKey("TipoEventoMetrologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("TipoEventoMetrologico");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Equipo", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("Equipos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.ResponsableInterno", "ResponsableInterno")
                        .WithMany("Equipos")
                        .HasForeignKey("ResponsableInternoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.TipoEquipo", "TipoEquipo")
                        .WithMany("Equipos")
                        .HasForeignKey("TipoEquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Ubicacion", "Ubicacion")
                        .WithMany("Equipos")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("ResponsableInterno");

                    b.Navigation("TipoEquipo");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoCalibracionDato", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", "EventoMetrologico")
                        .WithOne("EventoCalibracionDato")
                        .HasForeignKey("CGA.MetrologySystem.Domain.Entities.EventoCalibracionDato", "EventoMetrologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Laboratorio", "Laboratorio")
                        .WithMany("EventosCalibracion")
                        .HasForeignKey("LaboratorioId");

                    b.Navigation("EventoMetrologico");

                    b.Navigation("Laboratorio");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoMantenimientoActividad", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", "EventoMetrologico")
                        .WithMany("ActividadesMantenimiento")
                        .HasForeignKey("EventoMetrologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoMetrologico");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoMantenimientoDato", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", "EventoMetrologico")
                        .WithOne("EventoMantenimientoDato")
                        .HasForeignKey("CGA.MetrologySystem.Domain.Entities.EventoMantenimientoDato", "EventoMetrologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.TipoMantenimiento", "TipoMantenimiento")
                        .WithMany()
                        .HasForeignKey("TipoMantenimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoMetrologico");

                    b.Navigation("TipoMantenimiento");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Equipo", "Equipo")
                        .WithMany("EventosMetrologicos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.ResponsableInterno", "ResponsableInterno")
                        .WithMany("EventosMetrologicos")
                        .HasForeignKey("ResponsableInternoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.SubtipoEvento", "SubtipoEvento")
                        .WithMany("EventosMetrologicos")
                        .HasForeignKey("SubtipoEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.TipoEventoMetrologico", "TipoEventoMetrologico")
                        .WithMany("EventosMetrologicos")
                        .HasForeignKey("TipoEventoMetrologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("ResponsableInterno");

                    b.Navigation("SubtipoEvento");

                    b.Navigation("TipoEventoMetrologico");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoVerificacionDato", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", "EventoMetrologico")
                        .WithOne("EventoVerificacionDato")
                        .HasForeignKey("CGA.MetrologySystem.Domain.Entities.EventoVerificacionDato", "EventoMetrologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoMetrologico");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoVerificacionResultado", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", "EventoMetrologico")
                        .WithMany("ResultadosVerificacion")
                        .HasForeignKey("EventoMetrologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoMetrologico");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EvidenciaEventoMetrologico", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", "EventoMetrologico")
                        .WithMany("Evidencias")
                        .HasForeignKey("EventoMetrologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoMetrologico");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.FichaTecnicaEquipo", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Equipo", "Equipo")
                        .WithOne("FichaTecnica")
                        .HasForeignKey("CGA.MetrologySystem.Domain.Entities.FichaTecnicaEquipo", "EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.HojaVidaEquipo", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Equipo", "Equipo")
                        .WithOne("HojaVida")
                        .HasForeignKey("CGA.MetrologySystem.Domain.Entities.HojaVidaEquipo", "EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.NotificacionEnviada", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", "EventoMetrologico")
                        .WithMany()
                        .HasForeignKey("EventoMetrologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("EventoMetrologico");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.PlantillaEvento", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.TipoEquipo", "TipoEquipo")
                        .WithMany()
                        .HasForeignKey("TipoEquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.TipoEventoMetrologico", "TipoEventoMetrologico")
                        .WithMany()
                        .HasForeignKey("TipoEventoMetrologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoEquipo");

                    b.Navigation("TipoEventoMetrologico");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.PlantillaEventoItem", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.PlantillaEvento", "PlantillaEvento")
                        .WithMany("Items")
                        .HasForeignKey("PlantillaEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantillaEvento");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Infrastructure.Identity.UsuarioSistema", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Infrastructure.Identity.UsuarioSistema", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Infrastructure.Identity.UsuarioSistema", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Infrastructure.Identity.UsuarioSistema", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Equipo", b =>
                {
                    b.Navigation("CaracteristicasMetrologicas");

                    b.Navigation("ConfiguracionesControl");

                    b.Navigation("EventosMetrologicos");

                    b.Navigation("FichaTecnica");

                    b.Navigation("HojaVida");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", b =>
                {
                    b.Navigation("ActividadesMantenimiento");

                    b.Navigation("EventoCalibracionDato");

                    b.Navigation("EventoMantenimientoDato");

                    b.Navigation("EventoVerificacionDato");

                    b.Navigation("Evidencias");

                    b.Navigation("ResultadosVerificacion");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Laboratorio", b =>
                {
                    b.Navigation("EventosCalibracion");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.PlantillaEvento", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.ResponsableInterno", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("EventosMetrologicos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.SubtipoEvento", b =>
                {
                    b.Navigation("EventosMetrologicos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.TipoEquipo", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.TipoEventoMetrologico", b =>
                {
                    b.Navigation("ConfiguracionesControl");

                    b.Navigation("EventosMetrologicos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Ubicacion", b =>
                {
                    b.Navigation("Equipos");
                });
#pragma warning restore 612, 618
        }
    }
}
