// <auto-generated />
using System;
using CGA.MetrologySystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CGA.MetrologySystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418030318_AjustarTiposFechaMetrologicos")]
    partial class AjustarTiposFechaMetrologicos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.CaracteristicaMetrologicaEquipo", b =>
                {
                    b.Property<int>("CaracteristicaMetrologicaEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CaracteristicaMetrologicaEquipoId"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad")
                        .HasColumnType("text");

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("CaracteristicaMetrologicaEquipoId");

                    b.HasIndex("EquipoId");

                    b.ToTable("CaracteristicasMetrologicasEquipo");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.ConfiguracionControlEquipo", b =>
                {
                    b.Property<int>("ConfiguracionControlEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfiguracionControlEquipoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<string>("PeriodicidadUnidad")
                        .HasColumnType("text");

                    b.Property<int?>("PeriodicidadValor")
                        .HasColumnType("integer");

                    b.Property<bool>("PermitePorIngreso")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereControl")
                        .HasColumnType("boolean");

                    b.Property<int>("TipoEventoMetrologicoId")
                        .HasColumnType("integer");

                    b.HasKey("ConfiguracionControlEquipoId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("TipoEventoMetrologicoId");

                    b.ToTable("ConfiguracionesControlEquipo");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EquipoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CatalogoManejoOperacion")
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CondicionesOperacion")
                        .HasColumnType("text");

                    b.Property<string>("FabricanteLugarOrigen")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAdquisicion")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaPuestaFuncionamiento")
                        .HasColumnType("date");

                    b.Property<string>("Identificacion")
                        .HasColumnType("text");

                    b.Property<string>("MantenimientoFabricante")
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<int>("ResponsableInternoId")
                        .HasColumnType("integer");

                    b.Property<string>("Serie")
                        .HasColumnType("text");

                    b.Property<int>("TipoEquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("integer");

                    b.HasKey("EquipoId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("ResponsableInternoId");

                    b.HasIndex("TipoEquipoId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoCalibracionDato", b =>
                {
                    b.Property<int>("EventoCalibracionDatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventoCalibracionDatoId"));

                    b.Property<int>("EventoMetrologicoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCalibracion")
                        .HasColumnType("date");

                    b.Property<int?>("LaboratorioId")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroCertificado")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("RutaCertificado")
                        .HasColumnType("text");

                    b.HasKey("EventoCalibracionDatoId");

                    b.HasIndex("EventoMetrologicoId")
                        .IsUnique();

                    b.HasIndex("LaboratorioId");

                    b.ToTable("EventosCalibracionDato");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoMantenimientoActividad", b =>
                {
                    b.Property<int>("EventoMantenimientoActividadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventoMantenimientoActividadId"));

                    b.Property<string>("DescripcionActividad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventoMetrologicoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("EventoMantenimientoActividadId");

                    b.HasIndex("EventoMetrologicoId");

                    b.ToTable("EventosMantenimientoActividad");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", b =>
                {
                    b.Property<int>("EventoMetrologicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventoMetrologicoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ComentariosAdicionales")
                        .HasColumnType("text");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsExtraordinario")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoEquipoResultado")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaProxima")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JustificacionExtraordinario")
                        .HasColumnType("text");

                    b.Property<int>("ResponsableInternoId")
                        .HasColumnType("integer");

                    b.Property<int>("SubtipoEventoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEventoMetrologicoId")
                        .HasColumnType("integer");

                    b.HasKey("EventoMetrologicoId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("ResponsableInternoId");

                    b.HasIndex("SubtipoEventoId");

                    b.HasIndex("TipoEventoMetrologicoId");

                    b.ToTable("EventosMetrologicos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoVerificacionResultado", b =>
                {
                    b.Property<int>("EventoVerificacionResultadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventoVerificacionResultadoId"));

                    b.Property<bool>("Cumple")
                        .HasColumnType("boolean");

                    b.Property<string>("DescripcionItem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventoMetrologicoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("EventoVerificacionResultadoId");

                    b.HasIndex("EventoMetrologicoId");

                    b.ToTable("EventosVerificacionResultado");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Laboratorio", b =>
                {
                    b.Property<int>("LaboratorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LaboratorioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormaAcreditacion")
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .HasColumnType("text");

                    b.Property<string>("SitioWeb")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("LaboratorioId");

                    b.ToTable("Laboratorios");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProveedorId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("ProveedorId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.ResponsableInterno", b =>
                {
                    b.Property<int>("ResponsableInternoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResponsableInternoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cargo")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("ResponsableInternoId");

                    b.ToTable("ResponsablesInternos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.SubtipoEvento", b =>
                {
                    b.Property<int>("SubtipoEventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubtipoEventoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SubtipoEventoId");

                    b.ToTable("SubtiposEvento");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("TipoDocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoDocumentoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoDocumentoId");

                    b.ToTable("TiposDocumento");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.TipoEquipo", b =>
                {
                    b.Property<int>("TipoEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoEquipoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoEquipoId");

                    b.ToTable("TiposEquipo");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.TipoEventoMetrologico", b =>
                {
                    b.Property<int>("TipoEventoMetrologicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoEventoMetrologicoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoEventoMetrologicoId");

                    b.ToTable("TiposEventoMetrologico");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.TipoMantenimiento", b =>
                {
                    b.Property<int>("TipoMantenimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoMantenimientoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoMantenimientoId");

                    b.ToTable("TiposMantenimiento");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Ubicacion", b =>
                {
                    b.Property<int>("UbicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UbicacionId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UbicacionId");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.CaracteristicaMetrologicaEquipo", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Equipo", "Equipo")
                        .WithMany("CaracteristicasMetrologicas")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.ConfiguracionControlEquipo", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Equipo", "Equipo")
                        .WithMany("ConfiguracionesControl")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.TipoEventoMetrologico", "TipoEventoMetrologico")
                        .WithMany("ConfiguracionesControl")
                        .HasForeignKey("TipoEventoMetrologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("TipoEventoMetrologico");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Equipo", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("Equipos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.ResponsableInterno", "ResponsableInterno")
                        .WithMany("Equipos")
                        .HasForeignKey("ResponsableInternoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.TipoEquipo", "TipoEquipo")
                        .WithMany("Equipos")
                        .HasForeignKey("TipoEquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Ubicacion", "Ubicacion")
                        .WithMany("Equipos")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("ResponsableInterno");

                    b.Navigation("TipoEquipo");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoCalibracionDato", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", "EventoMetrologico")
                        .WithOne("EventoCalibracionDato")
                        .HasForeignKey("CGA.MetrologySystem.Domain.Entities.EventoCalibracionDato", "EventoMetrologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Laboratorio", "Laboratorio")
                        .WithMany("EventosCalibracion")
                        .HasForeignKey("LaboratorioId");

                    b.Navigation("EventoMetrologico");

                    b.Navigation("Laboratorio");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoMantenimientoActividad", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", "EventoMetrologico")
                        .WithMany("ActividadesMantenimiento")
                        .HasForeignKey("EventoMetrologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoMetrologico");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Equipo", "Equipo")
                        .WithMany("EventosMetrologicos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.ResponsableInterno", "ResponsableInterno")
                        .WithMany("EventosMetrologicos")
                        .HasForeignKey("ResponsableInternoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.SubtipoEvento", "SubtipoEvento")
                        .WithMany("EventosMetrologicos")
                        .HasForeignKey("SubtipoEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGA.MetrologySystem.Domain.Entities.TipoEventoMetrologico", "TipoEventoMetrologico")
                        .WithMany("EventosMetrologicos")
                        .HasForeignKey("TipoEventoMetrologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("ResponsableInterno");

                    b.Navigation("SubtipoEvento");

                    b.Navigation("TipoEventoMetrologico");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoVerificacionResultado", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", "EventoMetrologico")
                        .WithMany("ResultadosVerificacion")
                        .HasForeignKey("EventoMetrologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoMetrologico");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("CGA.MetrologySystem.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Equipo", b =>
                {
                    b.Navigation("CaracteristicasMetrologicas");

                    b.Navigation("ConfiguracionesControl");

                    b.Navigation("EventosMetrologicos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.EventoMetrologico", b =>
                {
                    b.Navigation("ActividadesMantenimiento");

                    b.Navigation("EventoCalibracionDato");

                    b.Navigation("ResultadosVerificacion");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Laboratorio", b =>
                {
                    b.Navigation("EventosCalibracion");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.ResponsableInterno", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("EventosMetrologicos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.SubtipoEvento", b =>
                {
                    b.Navigation("EventosMetrologicos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.TipoEquipo", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.TipoEventoMetrologico", b =>
                {
                    b.Navigation("ConfiguracionesControl");

                    b.Navigation("EventosMetrologicos");
                });

            modelBuilder.Entity("CGA.MetrologySystem.Domain.Entities.Ubicacion", b =>
                {
                    b.Navigation("Equipos");
                });
#pragma warning restore 612, 618
        }
    }
}
