name: CI - CGA Metrology System

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Verificar versión de .NET
        run: dotnet --version

      - name: Restaurar dependencias
        run: dotnet restore ./CGA.MetrologySystem/CGA.MetrologySystem.csproj

      - name: Compilar solución
        run: dotnet build ./CGA.MetrologySystem/CGA.MetrologySystem.csproj --no-restore --configuration Release

      - name: Ejecutar pruebas
        run: dotnet test ./CGA.MetrologySystem/CGA.MetrologySystem.csproj --no-build --configuration Release